from sqlmodel import Column, SQLModel, Field, TEXT
from typing import Optional
from datetime import datetime


class GenieSpace(SQLModel, table=True):
    """Represents a Databricks Genie Space mapping for a user.

    Attributes:
        user_id (str): The Microsoft Teams user ID (Primary Key).
        space_id (str): The unique identifier for the Genie Space (Primary Key).
        space_name (str): The human-readable name of the Genie Space.
        description (Optional[str]): An optional description of the space.
    """

    user_id: str = Field(
        default=None, max_length=255, sa_column=Column(TEXT, primary_key=True)
    )
    space_id: str = Field(default=None, primary_key=True, max_length=255)
    space_name: str = Field(default=None, max_length=255)
    description: Optional[str] = Field(default=None, max_length=1024)


class UserSelection(SQLModel, table=True):
    """Represents the active selected scope and context for a user.

    Attributes:
        user_id (str): The Microsoft Teams user ID (Primary Key).
        space_id (Optional[str]): The ID of the currently selected Genie Space.
        space_name (Optional[str]): The name of the currently selected Genie Space.
        conversation_id (Optional[str]): The active conversation ID in Databricks Genie.
        user_group_id (Optional[str]): The selected security group ID for Databricks credentials.
    """

    user_id: str = Field(default=None, primary_key=True, max_length=255)
    space_id: Optional[str] = Field(default=None, max_length=255)
    space_name: Optional[str] = Field(default=None, max_length=255)
    conversation_id: Optional[str] = Field(default=None, max_length=255)
    user_group_id: Optional[str] = Field(default=None, max_length=255)


class SecurityGroupMapping(SQLModel, table=True):
    """Represents a mapping between an Entra ID security group and Databricks credentials.

    Attributes:
        group_id (str): The Microsoft Entra ID group Object ID (Primary Key).
        group_name (str): The human-readable name of the group.
        databricks_client_id (Optional[str]): The OAuth client ID for the group.
        databricks_client_secret (Optional[str]): The OAuth client secret for the group.
    """

    group_id: str = Field(default=None, primary_key=True, max_length=255)
    group_name: str = Field(default=None, max_length=255)
    databricks_client_id: Optional[str] = Field(default=None, max_length=255)
    databricks_client_secret: Optional[str] = Field(default=None, max_length=255)


class QueryLog(SQLModel, table=True):
    """Represents a log entry for a user's question and the generated response/metadata.

    Attributes:
        id (Optional[int]): The auto-incrementing primary key for the log entry.
        user_name (Optional[str]): The display name of the Teams user.
        user_id (str): The Microsoft Teams user ID.
        scope_name (Optional[str]): The selected security scope/group name.
        space_name (Optional[str]): The name of the queried Genie Space.
        space_id (Optional[str]): The ID of the queried Genie Space.
        question (str): The natural language question asked by the user.
        sql_query (Optional[str]): The SQL query generated by Databricks Genie.
        start_time (Optional[datetime]): The timestamp when the request started.
        end_time (Optional[datetime]): The timestamp when the request completed/failed.
        exception (Optional[str]): The error/exception details if the request failed.
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    user_name: Optional[str] = Field(default=None, max_length=255)
    user_id: str = Field(max_length=255)
    scope_name: Optional[str] = Field(default=None, max_length=255)
    space_name: Optional[str] = Field(default=None, max_length=255)
    space_id: Optional[str] = Field(default=None, max_length=255)
    question: str = Field(sa_column=Column(TEXT))
    sql_query: Optional[str] = Field(default=None, sa_column=Column(TEXT))
    start_time: Optional[datetime] = Field(default=None)
    end_time: Optional[datetime] = Field(default=None)
    exception: Optional[str] = Field(default=None, sa_column=Column(TEXT))

